categories:
  path: /categories
  methods: [GET]
  controller: App\Controller\CategoryController::getAllCategories

category:
  path: /categories/{id}
  methods: [GET]
  controller: App\Controller\CategoryController::getCategory

category_delete:
  path: /categories/{id}
  methods: [DELETE]
  controller: App\Controller\CategoryController::deleteCategory


films:
  path: /film
  methods: [GET]
  controller: App\Controller\FilmController::getAllFilm

film_id:
  path: /film/{id}
  methods: [GET]
  controller: App\Controller\FilmController::getFilm

film_title:
  path: /film/{title}
  methods: [GET]
  controller: App\Controller\FilmController::getFilmTitle

film_delete:
  path: /film/{id}
  methods: [DELETE]
  controller: App\Controller\FilmController::deleteFilm

actor:
  path: /actor
  methods: [GET]
  controller: App\Controller\ActorController::getAllActor

actor_post:
  path: /actor
  methods: [POST]
  controller: App\Controller\ActorController::setActor

actor_id:
  path: /actor/{id}
  methods: [GET]
  controller: App\Controller\ActorController::getActorName

actor_delete:
  path: /actor/{id}
  methods: [DELETE]
  controller: App\Controller\ActorController::deleteActor

# login_user:
#   path: /login/{username}/{password}
#   methods: [POST]
#   controller: App\Controller\UserController::user_login
